apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: dev
spec:
  selector:
    app: microservice-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
